# Map emoji phổ biến trong review mua sắm → cảm xúc có nghĩa

EMOJI_SENTIMENT_MAP = {
    # Tích cực
    "😍" : "rất thích",
    "🥰" : "yêu thích",
    "😊" : "vui",
    "😁" : "vui",
    "🤩" : "tuyệt vời",
    "👍" : "tốt",
    "👌" : "ổn",
    "✅" : "tốt",
    "💯" : "hoàn hảo",
    "❤️" : "yêu thích",
    "💕" : "yêu thích",
    "🔥" : "tuyệt vời",
    "⭐" : "tốt",
    "🌟" : "xuất sắc",
    "🎉" : "vui mừng",
    "🙏" : "cảm ơn",
    "🥳" : "vui",
    "💪" : "mạnh mẽ",
    "🆗" : "ổn",
    # Tiêu cực
    "😡" : "tức giận",
    "🤬" : "rất tức giận",
    "😤" : "bực bội",
    "😒" : "không hài lòng",
    "😞" : "thất vọng",
    "😔" : "buồn",
    "👎" : "tệ",
    "🤮" : "rất tệ",
    "💩" : "tệ",
    "❌" : "không tốt",
    "⛔" : "không được",
    "🚫" : "từ chối",
    "😢" : "buồn",
    "😭" : "rất buồn",
    "🤦" : "thất vọng",
    "😠" : "tức giận",
    # Trung lập
    "🤔" : "suy nghĩ",
    "😐" : "bình thường",
    "😑" : "bình thường",
    "🤷" : "không biết",
    "📦" : "gói hàng",
    "🚚" : "giao hàng",
    "💰" : "tiền",
    "💸" : "tốn tiền",
}
