# Từ điển teencode phổ biến trong review mua sắm tiếng Việt

TEENCODE_DICT = {
    # Viết tắt phổ biến
    "cs"      : "có",
    "cx"      : "cũng",
    "qc"      : "quảng cáo",
    "ko"      : "không",
    "k"       : "không",
    "kh"      : "không",
    "kg"      : "không",
    "đc"      : "được",
    "dc"      : "được",
    "đk"      : "được",
    "vs"      : "với",
    "vd"      : "ví dụ",
    "ntn"     : "như thế nào",
    "nt"      : "nhắn tin",
    "mak"     : "mà",
    "mk"      : "mình",
    "mik"     : "mình",
    "mn"      : "mọi người",
    "ad"      : "admin",
    "sp"      : "sản phẩm",
    "hsd"     : "hạn sử dụng",
    "hh"      : "hàng hóa",
    "ck"      : "chuyển khoản",
    "tk"      : "tài khoản",
    "nv"      : "nhân viên",
    "dv"      : "dịch vụ",
    "cty"     : "công ty",
    "tl"      : "trả lời",
    "rep"     : "trả lời",
    "ib"      : "nhắn tin",
    "order"   : "đặt hàng",
    "ship"    : "giao hàng",
    "shipper" : "người giao hàng",
    "fake"    : "hàng giả",
    "shop"    : "cửa hàng",
    "sz"      : "kích cỡ",
    "size"    : "kích cỡ",
    "pic"     : "hình ảnh",
    "app"     : "ứng dụng",
    "web"     : "trang web",
    "acc"     : "tài khoản",
    "pass"    : "mật khẩu",
    "cmt"     : "bình luận",
    "fb"      : "facebook",
    "đt"      : "điện thoại",
    "đh"      : "đơn hàng",
    "khh"     : "khách hàng",
    "hd"      : "hướng dẫn",
    "tt"      : "thanh toán",
    "pttt"    : "phương thức thanh toán",
    "cod"     : "thanh toán khi nhận hàng",
    "hvc"     : "hàng về chậm",
    "lx"      : "liên xỉu",
    "sdt"     : "số điện thoại",
    "nx"      : "nữa",
    "chx"     : "chưa",
    "r"       : "rồi",
    "sd"      : "sử dụng",
    "ng"      : "người",
    "s"       : "sao",
    "thui"    : "thôi",
    "j"       : "gì",
    "xog"     : "xong",
    "lm"    : "làm",
    "t"       : "tôi",
    "cskh"  : "chăm sóc khách hàng",
    "th"    : "thôi",
    "kv"    : "khu vực",
    "hcm"   : "Hồ Chí Minh",
    "tphcm" : "thành phố Hồ Chí Minh",
    "nvcskh" : "nhân viên chăm sóc khách hàng",
    "ngk"   : "người khác",
    "tn"    : "thế nào",
    "v"     : "vậy",
    "cgi"   : "cái gì",
    "wed"   : "trang web",
    "thk"   : "thằng",
    "dg"    : "đang",
    "trl"   : "trả lời",
    "hs"    : "học sinh",
    "sv"    : "sinh viên",
    "hssv"  : "học sinh sinh viên",
    "hs&sv" : "học sinh sinh viên",
    "khog"  : "không",
    "qcao"   : "quảng cáo",
    "kiu"   : "kêu",
    "ae"    : "anh em",
    "dn"    : "doanh nghiệp",
    "lk"    : "liên kết",
    "ngta"   : "người ta",
    "dhs"   : "không hiểu sao",
    "đhs"   : "không hiểu sao",
    "tt"    : "thanh toán",
    "tg"    : "thời gian",
    "trc"   : "trước",
    "tr"    : "trời",
    "dvkh"  : "dịch vụ khách hàng",
    "tmdt"  : "thương mại điện tử",
    "nâu"   : "lâu",
    "wa"    : "quá",
    "nvtv"   : "nhân viên tư vấn",
    "lh"    : "liên hệ",
    "mìh"   : "mình",
    "hàg"   : "hàng",
    "khug"  : "khung",
    "cũg"   : "cũng",
    "cah"   : "canh",
    "c.bi"  : "chuẩn bị",
    "đúg"   : "đúng",
    "tưởg"  : "tưởng",
    "đăg"   : "đăng",
    "thg"   : "thằng",
    "kh"    : "khách hàng",
    "hn"    : "Hà nội",
    "củng"  : "cũng",
    "giáo" : "giao",
    "thaay": "thấy",
    "om"    : "ôm",
    "mồng"  : "mong",
    "đủng"  : "đỉnh",
    "th.viên"   : "thành viên",
    "ah"    : "à",
    "nta"   : "người ta",
    "dcj"   : "được gì",
    "mún"    : "muốn",
    "nvien" : "nhân viên",
    "aap"   : "ứng dụng",
    "ik"    :   "ý",
    "z"    :   "gì",
    "ròi"   :   "rồi",
    "dt"     : "điện thoại",

    


    



    
    
    
    



    # Cảm xúc / Đánh giá
    "ok"      : "ổn",
    "oce"     : "ổn",
    "oke"     : "ổn",
    "okela"   : "ổn",
    "xịn"     : "tốt",
    "xịn xò"  : "tốt",
    "chill"   : "thoải mái",
    "cute"    : "dễ thương",
    "pro"     : "giỏi",
    "vl"      : "rất",
    "vch"     : "rất",
    "vcl"     : "rất",
    "bt"      : "bình thường",
    "bth"     : "bình thường",
    "hok"     : "không",
    "hem"     : "không có",
    "hổng"    : "không",
    "hông"    : "không",
    "hong"    : "không",
    "hog"    : "không",
    "thik"    : "thích",
    "iu"      : "yêu",
    "ưng"     : "thích",
    "ghét"    : "không thích",
    "nản"     : "thất vọng",
    "tệ"      : "tệ",
    "chán"    : "thất vọng",
    


    # Chửi thề / Từ nhấn mạnh tiêu cực
    # Nhóm này là tín hiệu NEGATIVE rất mạnh — xem hướng dẫn annotation
    "dm"      : "thất vọng tức giận",
    "đm"      : "thất vọng tức giận",
    "dmm"     : "thất vọng tức giận",
    "đmm"     : "thất vọng tức giận",
    "đcm"     : "thất vọng tức giận",
    "đmcs"    : "thất vọng tức giận",
    "má"      : "thất vọng tức giận",
    "djt"      : "thất vọng tức giận",
    "đcmm" : "thất vọng tức giận",
    "vkl"     : "rất tệ",
    "cc"      : "rất tệ",
    "ccc"      : "rất tệ",
    "cặc"     : "rất tệ",
    "c.ặ.c"     : "rất tệ",
    "cac"     : "rất tệ",
    "cak"     : "rất tệ",
    "cl"      : "rất tệ",
    "lol"     : "rất tệ",
    "loll"     : "rất tệ",
    "loz"      : "rất tệ",
    "lồn"     : "rất tệ",
    "đéo"     : "rất tệ",
    "đ"      : "rất tệ",
    "éo"     : "rất tệ",
    "như l"     : "rất tệ",
    "đéo hiểu" : "rất tệ",
    "deo"     : "rất tệ",
    "dell"      : "rất tệ",
    "clgt"      : "rất tệ",
    "qq"        : "rất tệ",
    "cứt"      : "tệ",
    "kít"      : "tệ",
    "như c"      : "tệ",
    "nhu c"      : "tệ",
    "như cặc"      : "tệ",
    "đầu bùi"    : "tệ",
    "đb"         : "tệ",
    "fake"        : "hàng giả",
    "ha.ch"        : "rất tệ",
    "shjt"          : "rất tệ",
    "con c" : "thất vọng tức giận",
    "con cu" : "thất vọng tức giận",
    "c*"    :   "thất vọng tức giận",
    "conk@c" : "thất vọng tức giận",
    "đit" : "thất vọng tức giận",
    "hạch" : "tệ",
    "cailon ma m"      : "tệ",
    "đau buôi" : "tệ",
    "cặt" : "tệ",
    
    


    

    



    # Thời gian
    "nay"     : "hôm nay",
    "qua"     : "hôm qua",
    "t2"      : "thứ hai",
    "t3"      : "thứ ba",
    "t4"      : "thứ tư",
    "t5"      : "thứ năm",
    "t6"      : "thứ sáu",
    "t7"      : "thứ bảy",
    "cn"      : "chủ nhật",
    
}
