# Từ điển teencode phổ biến trong review mua sắm tiếng Việt

TEENCODE_DICT = {
    # Viết tắt phổ biến
    "ko"      : "không",
    "k"       : "không",
    "kh"      : "không",
    "kg"      : "không",
    "đc"      : "được",
    "dc"      : "được",
    "đk"      : "được",
    "vs"      : "với",
    "vd"      : "ví dụ",
    "ntn"     : "như thế nào",
    "nt"      : "nhắn tin",
    "mk"      : "mình",
    "mik"     : "mình",
    "m"       : "mình",
    "mn"      : "mọi người",
    "ad"      : "admin",
    "sp"      : "sản phẩm",
    "hsd"     : "hạn sử dụng",
    "hh"      : "hàng hóa",
    "ck"      : "chuyển khoản",
    "tk"      : "tài khoản",
    "nv"      : "nhân viên",
    "dv"      : "dịch vụ",
    "cty"     : "công ty",
    "tl"      : "trả lời",
    "rep"     : "trả lời",
    "ib"      : "nhắn tin",
    "order"   : "đặt hàng",
    "ship"    : "giao hàng",
    "shipper" : "người giao hàng",
    "fake"    : "hàng giả",
    # Cảm xúc / Đánh giá
    "ok"      : "ổn",
    "oce"     : "ổn",
    "oke"     : "ổn",
    "okela"   : "ổn",
    "xịn"     : "tốt",
    "xịn xò"  : "tốt",
    "chill"   : "thoải mái",
    "cute"    : "dễ thương",
    "pro"     : "giỏi",
    "vl"      : "rất",
    "vch"     : "rất",
    "cl"      : "chất lượng",
    "bt"      : "bình thường",
    "bth"     : "bình thường",
    "hok"     : "không",
    "hem"     : "không có",
    "hổng"    : "không",
    "hông"    : "không",
    "hong"    : "không",
    # Thời gian
    "nay"     : "hôm nay",
    "qua"     : "hôm qua",
    "t2"      : "thứ hai",
    "t3"      : "thứ ba",
    "t4"      : "thứ tư",
    "t5"      : "thứ năm",
    "t6"      : "thứ sáu",
    "t7"      : "thứ bảy",
    "cn"      : "chủ nhật",
}
